# Generated by Django 3.0.2 on 2020-02-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answer_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='votes',
            new_name='points',
        ),
    ]
