# Generated by Django 2.2.1 on 2020-02-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20200205_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
