# Generated by Django 2.2.1 on 2020-02-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_question_max_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(default=False, max_length=2),
        ),
    ]
