# Generated by Django 3.0.2 on 2020-02-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_choice_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
    ]
