# Generated by Django 3.0.8 on 2020-12-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20201122_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='question.Question'),
        ),
    ]
